myItem: response.o code.o mastermind.o main.o
	g++ main.o response.o code.o mastermind.o -o myItem

main.o: main.cpp code.h response.h mastermind.h
	g++ -c main.cpp

response.o: response.cpp response.h code.h mastermind.h
	g++ -c response.cpp

code.o: code.cpp code.h mastermind.h
	g++ -c code.cpp

mastermind.o: mastermind.cpp mastermind.h
	g++ -c mastermind.cpp

clean:
	rm main.o response.o code.o mastermind.o
